# Generated by Django 2.1.7 on 2019-04-23 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('content_type', models.PositiveSmallIntegerField(choices=[(1, 'Audio'), (2, 'Video'), (3, 'Text')])),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_bitrate', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('video_subtitles', models.FileField(blank=True, null=True, upload_to='subtitles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Content')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Page')),
            ],
            options={
                'ordering': ('-order',),
            },
        ),
        migrations.AddField(
            model_name='content',
            name='pages',
            field=models.ManyToManyField(related_name='content', through='base.PageContent', to='base.Page'),
        ),
    ]
